cache:
  - node_modules
environment:
  matrix:
    - platform: x64
install:
  - ps: Install-Product node 6 x64
  - set CI=true
  - npm install -g flow-typed
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn
image: Visual Studio 2015
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run dist
