cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: 8lOYxuReE4oWUZaa9hj9pWvmE+blMbrFYfav7+ot2P3IQXCPGaf6hS2jI6ruDZc/
  matrix:
    - platform: x64
install:
  - ps: Install-Product node 9 x64
  - set CI=true
  - npm install -g flow-typed
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn
image: Visual Studio 2015
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run dist
