os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: 8lOYxuReE4oWUZaa9hj9pWvmE+blMbrFYfav7+ot2P3IQXCPGaf6hS2jI6ruDZc/
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run build